# Generated by Django 4.0.4 on 2022-04-24 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabsite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
